version: 2.1

orbs:
  python: circleci/python@2.1.1
  
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.7
   
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run tests utils
          command: python -m unittest tests.utils_test
      - run:
          name: Run tests tools_for_pytorch
          command: python -m unittest tests.toold_test
      - run:    
          command: python -m unittest tests.hypermodel_test
      - run:    
          command: python -m unittest tests.classes_test
          
          
workflows:
  sample: 
    jobs:
      - build-and-test
