version: 2.1

orbs:
  python: circleci/python@2.0.3
  
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8.10
   
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run tests
          command: python -m unittest tests.utils_test
          
          
          
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
